CONFIG_NAME: private-chain
PRESET_BASE: mainnet
GENESIS_FORK_VERSION: 0x20000089
GENESIS_DELAY: 0
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000090
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 0
CAPELLA_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x20000092
DENEB_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x20000093
ELECTRA_FORK_EPOCH: 18446744073709551615
ELECTRA_FORK_VERSION: 0x20000094
FULU_FORK_EPOCH: 18446744073709551615
FULU_FORK_VERSION: 0x20000095
SECONDS_PER_SLOT: 6
SLOTS_PER_EPOCH: 8
MIN_GENESIS_TIME: 0
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1
DEPOSIT_CHAIN_ID: 32382
DEPOSIT_NETWORK_ID: 32382
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
